language: python

python:
- '2.7'

services:
- docker

before_install:
- sudo apt-get update

- sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
- docker build . -t eoxserver --add-host=browse:127.0.0.1

script:
- docker run -it --rm --name test-eoxserver -p 8081:80 -v "${PWD}/../eoxserver/":/usr/lib/python2.6/site-packages/eoxserver/ -v "${PWD}/../autotest/data/":/opt/instance/autotest/data/ -v "${PWD}/../autotest/logs/":/opt/instance/autotest/logs/ --tmpfs /tmp:rw,exec,nosuid,nodev -h browse --add-host=browse:127.0.0.1 eoxserver /bin/bash -c "echo \"TEST_RUNNER = 'eoxserver.testing.core.EOxServerTestRunner'\" >> /opt/instance/autotest/settings.py && python /opt/instance/manage.py test 'control|IngestModelInGeotiffBrowseOnSwift,SeedModelInGeotiffBrowseOnSwift,IngestFootprintBrowseReplaceOnSwift,IngestFootprintBrowseMergeOnSwift' -v2"
before_deploy:
- docker run -it --rm --name build-eoxserver -v "${PWD}/../":/opt/instance --tmpfs /tmp:rw,exec,nosuid,nodev -h browse --add-host=browse:127.0.0.1 eoxserver /bin/bash -c "yum update && yum install -y rpmdevtools && cd /opt/instance/ && python setup.py bdist_rpm"

deploy:
  provider: releases
  api_key:
    secure: QPKKSL6Vc5iN7zt1WtnTZ2CbHX4V5RzpLS9NkR+bUp+fTP24i7twt4J6c2yRjhE3IgSLwj08ESoe3yZW5HqKVB8WhMd8+E/vfkekbllIU74i51hXSlpIS58xNtI8PkT9WE9eYIi90QEbN6es1YjhtBiPYI1WZXg3NC9TscffGfY=
  file_glob: true
  file: ../dist/*.rpm
  skip_cleanup: true
  draft: true
  on:
    tags: true

notifications:
  slack:
    secure: axWg6MRTsvJByFcSG84Birbc3bNFWXnmmA45Rp/4IyBVklI3ytk0WmVx3Qqlf/vz2xfZHdRde4Je/Y+0ufioRY1e3fEl3J/IbcG1CeUcNPn5ghCmn8rJe+ptsFZQYY4uLsX9mWd74Q7xP12kxPQkRKHvpswYtmOhiYxZNEltcIk=
